name: weatherdata_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - aiohttp=3.9.5
  - pydantic=2.7.3
  - requests=2.32.3
  - pip
  - pip:
      - langchain==0.2.3
      - openai==1.33.0
      - python-dotenv==1.0.1
      - tenacity==8.3.0
      - typing-extensions==4.12.2
